# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Math Utility Repo applying CI   #cach ta dat ten cho dat ten tat cac lenh o duoi

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 18 #sua jdk 18
      uses: actions/setup-java@v3
      with:
        java-version: '18' # sua jdk 18
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven (tao .jar .war)   #.4 Muon maven va chay lenh mvn packege
      run: mvn -B package --file pom.xml #xoa 2 dong cuoi
    - name: Distribute jar-war file # Gửi file .jar .war đi đâu, CD nhảy vào ...
      run: mkdir staging && cp target/*.jar staging # tạo thư mục staging chứa file .jar .war sau khi build      
     
    - name: Make hyperlink to jar-war file # Tạo hyperlink để download build 
      uses: actions/upload-artifact@v1
      with:
          name: Hay -Download-Jar-o-day  #day la duong link tro toi file .jar .war
          path: staging                  # neu duoc build thanh cong
      

      
      
